const express = require('express')
require('dotenv').config()
const {errorHandler} = require('./middleware/errorMiddleware')
const connectDB = require('./config/db')
const port = process.env.PORT || 5000
connectDB()
const app = express()
app.use(express.json())
app.use(express.urlencoded({extended:false}))
app.use('/api/review',require('./routes/reviewRoutes'))
app.use('/api/user',require('./routes/userRoutes'))
app.use('/spotify',require('./routes/spotifyRoutes'))
app.use(errorHandler)
app.listen(port,()=>console.log(`Server started on port ${port}`))
